services:
  # Add more containers below (nginx, postgres, etc.)
  dualdb-back:
    container_name: dualdb-back
    build:
      context: ./dualdb-back
      dockerfile: Dockerfile

    # Set envrionment variables based on the .env file
    env_file:
      - dualdb-back/.env
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - dualdb-server
      - mongodb

  dualdb-server:
    image: postgres
    container_name: dualdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dualdb
      POSTGRES_PASSWORD: azqswx12
    volumes:
      - dualdb-server:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: azqswx12
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db

volumes:
  dualdb-server:
  pgadmin-data:
  mongodb-data: