version: '3.8'

services:
  dualdb-back:
    container_name: dualdb-back
    build:
      context: ./dualdb-back
      dockerfile: Dockerfile
    env_file:
      - dualdb-back/.env
    restart: always
    ports:
      - 5000:5000

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=userAdmin
      - MONGO_INITDB_ROOT_PASSWORD=userPassword

# volumes:
#   mongodb-data:
