
services:

# Add more containers below (nginx, postgres, etc.)
  dualdb-back:
    container_name: dualdb-back
    build:
      context: ./dualdb-back
      dockerfile: Dockerfile

    # Set envrionment variables based on the .env file
    env_file:
      - dualdb-back/.env
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - dualdb-server

  dualdb-front:
    container_name: dualdb-front
    build:
      context: ./dualdb-front
      dockerfile: Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    env_file:
      - dualdb-front/.env
    restart: always
    ports:
      - 3000:3000

  dualdb-server:
    image: postgres
    container_name: dualdb-server
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dualdb
      POSTGRES_PASSWORD: strong-password
    volumes:
      - dualdb-server:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  dualdb-server:
  pgadmin-data:

  # my-api:
  #     container_name: my-api
  #     image: ghcr.io/fredericlauss/fullnextapp-api:main

  #     # Set envrionment variables based on the .env file
  #     env_file:
  #       - .env
  #     restart: always
  #     ports:
  #       - 5000:5000
  #     depends_on:
  #       - mongo
    